name: Daily Security Pipeline

on:
  schedule:
    - cron: '0 0 * * *'  
  workflow_dispatch:

jobs:
  DependenciesAnalysis:
    name: Dependencies & Semgrep Analysis
    runs-on: ubuntu-latest
    container:
      image: returntocorp/semgrep

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run OSV Scanner
        uses: google/osv-scanner-action@v1

      - name: Run Semgrep analysis (Java ruleset)
        run: semgrep --config p/java --sarif -o semgrep-report.sarif

      - name: Upload SARIF report
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: semgrep-report.sarif
  SourceCodeAnalysis:
    name: Source Code Scan (OSV Only)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run OSV Scanner
        uses: google/osv-scanner-action@v1

      - name: Upload SARIF report
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: osv.scanner.sarif

