name: Daily Security Pipeline

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:  

jobs:
  DependenciesAnalysis:
    name: Dependencies & Semgrep Analysis
    runs-on: ubuntu-latest
    container:
      image: returntocorp/semgrep

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install OSV Scanner
        run: |
          curl -sSfL https://github.com/google/osv-scanner/releases/latest/download/osv-scanner-linux-amd64 -o osv-scanner
          chmod +x osv-scanner
          mv osv-scanner /usr/local/bin/

      - name: Run OSV Scanner
        run: |
          osv-scanner --lockfile=**/package-lock.json --format=sarif > osv-report.sarif

      - name: Run Semgrep analysis (Java ruleset)
        run: semgrep --config p/java --sarif -o semgrep-report.sarif

      - name: Upload Semgrep SARIF report
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: semgrep-report.sarif

      - name: Upload OSV SARIF report
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: osv-report.sarif

  SourceCodeAnalysis:
    name: Source Code Scan (OSV Only)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install OSV Scanner
        run: |
          curl -sSfL https://github.com/google/osv-scanner/releases/latest/download/osv-scanner-linux-amd64 -o osv-scanner
          chmod +x osv-scanner
          sudo mv osv-scanner /usr/local/bin/

      - name: Run OSV Scanner
        run: |
          osv-scanner --lockfile=**/package-lock.json --format=sarif > osv-report.sarif

      - name: Upload SARIF report
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: osv-report.sarif

